twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        navigation: '@App\Services\TwigLoad\Navigation'
        images: '@App\Services\TwigLoad\Svg'
        restrictetList:
            - salt
            - password
            - roles
            - username
            - isnew
            - token
            - userresult
            - language
            - subjectresult
